# Generated by Django 5.0.3 on 2024-03-29 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dColaboradores',
            fields=[
                ('idColaborador', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=255)),
                ('cargoFuncao', models.CharField(max_length=255)),
                ('CPF', models.CharField(blank=True, max_length=14, null=True)),
                ('tipoContrato', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custoMes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dtAdmissao', models.DateTimeField()),
                ('dtDemissaoAlteracao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='fPonto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField()),
                ('entrada', models.DateTimeField()),
                ('saidaIntervalo', models.DateTimeField(blank=True, null=True)),
                ('entradaIntervalo', models.DateTimeField(blank=True, null=True)),
                ('saida', models.DateTimeField(blank=True, null=True)),
                ('saldoDiario', models.CharField(blank=True, max_length=255, null=True)),
                ('justificado', models.BooleanField(default=False)),
                ('entradaCorrecao', models.BooleanField(default=False)),
                ('saidaIntervaloCorrecao', models.BooleanField(default=False)),
                ('entradaIntervaloCorrecao', models.BooleanField(default=False)),
                ('saidaCorrecao', models.BooleanField(default=False)),
                ('idColaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.dcolaboradores')),
            ],
        ),
        migrations.CreateModel(
            name='fPontoCorrecoes',
            fields=[
                ('idCorrecao', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField()),
                ('horarioSubstituido', models.DateTimeField()),
                ('horario', models.DateTimeField()),
                ('idColaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.dcolaboradores')),
            ],
        ),
    ]
