# Generated by Django 5.0.3 on 2024-03-29 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fponto',
            name='idColaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponto_colaborador', to='employees.dcolaboradores'),
        ),
    ]
